### ISSUE TITLE
Порядок выдачи комментариев в теме СВОДД

### ISSUE THREAD

**Issue by audetv** [terratensor/svodd#200]
Проверить сортировку
https://svodd.ru/bolshaya-svoddnaya-tema?page=614
#441012
#441011

По времени и по номеру комментария?

<details><summary>2023-06-09_15-34-14</summary>
<p>

![2023-06-09_15-34-14](https://github.com/audetv/fct-search/assets/10896447/cffca088-2117-4da3-9d21-8a626b5864d0)

</p>
</details>

**Comment by iprst** [comment]
У меня сортировка отображается верно. Соответствует сайту.

**Comment by audetv** [comment]
Да, у меня тоже соответствует, но был момент, когда они были поменяны местами, я зафиксировал, хочу потом посмотреть откуда такие результаты. Эффект такой был замечен, когда они были двумя последними комментариями. Посмотрю потом сортировку.

**Comment by audetv** [comment]
<details><summary>2023-06-09_15-34-14</summary>
<p>

![2023-06-09_15-34-14](https://github.com/audetv/fct-search/assets/10896447/cffca088-2117-4da3-9d21-8a626b5864d0)


</p>
</details> 
Если пообновлять страницу F-5 у меня прыгают комментарии , забавно. точно сортировка.

**Comment by iprst** [comment]
> Если пообновлять страницу F-5, у меня прыгают комментарии , забавно. точно сортировка.

Подтверждаю, через 3-4 перезагрузки страницы есть прыжок между комментариями Сергея с номерами …11 и …12
