### ISSUE TITLE
Формат видео для сайта: mp4 / webm

### ISSUE THREAD

**Issue by audetv** [terratensor/svodd#207]
Скопированное сообщение ★ https://svodd.ru/n3hl3G4Z

> Алексей или Сергей, кто занимается svodd.ru, сконвертируйте расширение видео denpobedy.mp4 в webm, будет намного лучше, https://convertio.co/ru/download/b8868efb1bb983af8aced7661a6ac25546c000/ можете с этого ресурса скачать уже сконвертированный

Cохранил ссылку на яндекс диск: https://disk.yandex.ru/i/qz7bV1n8Tzo_Fg

**Comment by iprst** [comment]
Часть старых яблок возможно не смогут воспроизвести webm, поддержка есть начиная с операционки iOS 15 и соответсвующей версии Safari. Но это не критично, можно заменить на главной. Можно вообще убрать, а к 22-му что-то перерисовать новое.

**Comment by audetv** [comment]
Я посмотрю в ближайшее время и разместим два варианта, я почти уверен, что в теге video src оба варианта можно размесить и устройство (браузер) будет грузить наилучший вариант. Надо будет глянуть documentation.

**Comment by iprst** [comment]
Там что-то наподобие

**Comment by audetv** [comment]
> Можно вообще убрать, а к 22-му что-то перерисовать новое.

да, согласен можно, дата не праздничная, но знаменательная, помним. Можем отметить новым видео. Пока нет идей, подумаю, с парсером разбираюсь)

**Comment by iprst** [comment]
> дата не праздничная, но знаменательная, помним

Можно в теме спросить.

**Comment by iprst** [comment]
Теперь по умолчанию открывается webm

**Comment by iprst** [comment]
Есть мысль оставить видео на главной, как оно есть (то есть не рисовать ничего для 22 июня), но убрать в каком-то недалёком будущем из страницы выдачи, чтобы оно служило чисто банером на главной, а выдача стала более доступной для работы.

**Comment by iprst** [comment]
> Пока оставляем, жду сигнала, когда убирать из поисковой выдачи.

Ага, может на форуме кто-то даст ОС. Пусть висит.
