### ISSUE TITLE
Публикация тегов на ФКТ парсится выдачей поисковика

### ISSUE THREAD

**Issue by iprst** [terratensor/svodd#209]
Комментарий [#441541](https://фкт-алтай.рф/qa/question/view-4295#:~:text=10:57%2021.06.2023) в [большой своддной теме](https://svodd.ru/bolshaya-svoddnaya-tema?sort=-date) содержит два тега для демонстрации: 
```
<source src="https://static.svodd.ru/video/denpobedy.webm" type="video/webm" />
<source src="https://static.svodd.ru/video/denpobedy.mp4" type="video/mp4" />
```

Поисковик обрезает начало этих тегов, поскольку на сайте ФКТ нет собственного тега «код» и специального представления кода «как есть» не предусмотрено. 

Оригинал:

![image](https://github.com/terratensor/svodd/assets/129882753/affc63a6-d65b-4098-b642-0e3491cd4a1d)

Выдача:

![image](https://github.com/terratensor/svodd/assets/129882753/ab9b1d06-deaa-4ce9-89bf-a46f5c99f5db)

**Comment by iprst** [comment]
Огонь!

**Comment by audetv** [comment]
https://svodd.ru/?search%5Bquery%5D=441541+&search%5Bmatching%5D=&search%5Bmatching%5D=in&search%5Bdate%5D=&search%5Bdictionary%5D=0

**Comment by audetv** [comment]
тега «код» не добавлял, но такие теги будут видны.

**Comment by iprst** [comment]
Мэджик
