### ISSUE TITLE
Открываем новую тему СВОДД 39

### ISSUE THREAD

**Issue by iprst** [terratensor/svodd#228]
ПРОДОЛЖЕНИЕ ОБСУЖДЕНИЯ СВОДД 39
[https://фкт-алтай.рф/qa/question/view-3158](https://xn----8sba0bbi0cdm.xn--p1ai/qa/question/view-5723)

Добавляю её в систему:

![image](https://github.com/terratensor/svodd/assets/129882753/cfaf1b95-5c18-4e11-9b00-4ffbc68d16cf)

**Comment by iprst** [comment]
![image](https://github.com/terratensor/svodd/assets/129882753/a54ec946-898b-4ae4-8785-1d7073ccb07f)

**Comment by iprst** [comment]
Тема обновилась, svood.ru подцепил, телеграм подцепил. Системы работают в норме.

**Comment by audetv** [comment]
Неожиданно, предполагал, что будет ошибка) сегодня в течении дня пару раз фиксил алгоритм, и обновил fct-paser? чтобы он тоже знал о новой теме, теоретически существует пару сценариев, что система отвалится, но они не случились, это хорошо. Посмотрю, что по логам, и спокойно еще обдумаю эти пару сценариев, возможно они и не случаться.

**Comment by iprst** [comment]
Я решил раз вы уже опубликовали всю схему добавления, сразу и проверить — если бы не открылась, то я пока не добавлял бы комментарий в старой теме об открытии, а ошибка послужила бы сигналом, как и договаривались, тогда пришлось бы править что-то вручную. А в случае если всё сработает, то и вам беспокойства не потребуется.

**Comment by audetv** [comment]
>  то я пока не добавлял бы комментарий в старой теме об открытии, а ошибка послужила бы сигналом, как и договаривались, тогда пришлось бы править что-то вручную. 

Да, отлично, это хороший вариант при возникновении ошибки. Супер.

Все хорошо прошло. 
Просто я обновлял код и каждый раз после приходило озарение, что вот тут еще может быть ошибка и вот тут может вылететь исключение и надо проверить. И так довел до результата, и все прошло успешно. Система усложнилась, много сервисов работает в связке, но теперь уже не придется возиться руками из консоли при обновлении темы. Так и до автоматического открытия по условной фразе дойдут руки ))

**Comment by iprst** [comment]
> Так и до автоматического открытия по условной фразе дойдут руки ))

Шикарно.

**Comment by audetv** [comment]
Не установилась дата начала темы в статистике, я это вручную из консоли запустил, но это не страшно, придумаю и исправлю, просто надо запускать обновление даты позже, после того как будет спарсен первый комментарий, т.е. через минуту. Я об этом уже подумал после последнего обновления, но:

главное, что не возникло критических ошибок, приводящих к остановке выполнения скрипта, например обращение к еще несуществующим данным, такие сценарии надо оборачивать в исключения и обрабатывать, иначе приложение падает, значит все обернул)

И сейчас самый критичный момент, что в форме при переключении можно указать «левый» номер комментария, и это приведет к ошибке в графике статистки, на остальном не отразиться, вопрос подцепится и телега поедет… 

Но даже левый номер не приведет к падению приложения, и этот номер потом можно исправить в консоли, не критично и график станет актуальным.

**Comment by iprst** [comment]
> Не установилась дата начала темы в статистике, я это вручную из консоли запустил, но это не страшно, придумаю и исправлю, просто надо запускать обновление даты позже, после того как будет спарсен первый комментарий, т.е. через минуту. Я об этом уже подумал после последнего обновления, но:
> 
> И сейчас самый критичный момент, что в форме при переключении можно указать «левый» номер комментария, и это приведет к ошибке в графике статистки, на остальном не отразиться, вопрос подцепится и телега поедет…

Нужно добавление id первого комментария сделать автоматическим, без добавления вручную — запускать парсер на новую тему и забирать оттуда первый комментарий. При этом можно также брать номер темы N+1 из уже имеющейся статистики, и присваивать новый номер автоматически. Таким образом администратору нужно лишь добавить адрес новой темы после размещения в ней первого комментария, дождаться подключения и опубликовать приглашение в старой теме.
