### ISSUE TITLE
Улучшение алгоритма смены темы СВОДД

### ISSUE THREAD

**Issue by audetv** [terratensor/svodd#230]
Да, можно так и сделать, к следующей теме так и сделаю. 
Номер комментария в новом вопросе можно брать тот, который по ИД больше, чем спарсенный предыдущий номер комментария из своддной темы. Номер комментария нужен для графика статистики, и для случая, если будет сделано переключение на вопрос, в котором уже были комментарии ранее, т.е. первый открывающий комментарий темы в вопросе может быть не первым комментарием вообще.

Передаем новый урл вопроса в форму, нажимаем переключить, запускается переключение, для отработки всех сервисов надо некоторое время — 1-2 минуты, как только сервисы отработают, вопрос подцепятся, график обновиться. 
Так и сделаю.

_Originally posted by @audetv in https://github.com/terratensor/svodd/issues/228#issuecomment-1677902976_
            

- [x] Автоматическая генерация следующего номера темы
- [x] Автоматическая установка ИД комментария, открывающего тему

**Comment by iprst** [comment]
Скорее всего сегодня или завтра будем открывать следующую тему, поэтому будет проверена работа новой формы с двумя полями.

**Comment by iprst** [comment]
Новая форма с двумя полями работает без нареканий, [тема открыта](https://github.com/terratensor/svodd/issues/233) без сложностей, все модули за которыми смог проследить подключились и работают — статистика обновилась, телеграм подключился.

**Comment by audetv** [comment]
Выгрузил Develop #234

> Доработан алгоритм смены темы.
Теперь не надо указывать номер начального комментария при смене темы, получение и установка номера происходит в автоматическом режиме.


Проверим при смене следующей темы.
Если все пройдет успешно, закроем issue

**Comment by iprst** [comment]
[Испытан](https://github.com/terratensor/svodd/issues/239) механизм добавления темы одним полем в кабинете.
Всё работает штатно. 

Сначала была замечена проблема: статистика дала ошибочный подсчёт комментариев — было засчитано, что в новой теме ноль комментариев, таким образом ноль процентов, но через полминуты всё было пересчитано, первый комментарий засчитался как 100% по обычному распорядку. Сейчас всё работает в нормальном режиме.

**Comment by audetv** [comment]
> Сначала была замечена проблема: статистика дала ошибочный подсчёт комментариев — было засчитано, что в новой теме ноль комментариев, таким образом ноль процентов, но через полминуты всё было пересчитано, первый комментарий засчитался как 100% по обычному распорядку. Сейчас всё работает в нормальном режиме.

Хорошо, это запланированный сценарий. Парсер собирает данные с ФКТ 1 раз в минуту по крон, после нажатия кнопки «смена темы» происходит запись в БД о новом адресе, но новых комментариев в БД может еще не быть, далее по расписанию (cron) парсер уже подтягивает новые комментарии из новой(только что сменённой) темы и обновляется график и статистику.  Т.е. процесс смены происходит в несколько этапов, примерно в течение 1 минуты. 
Посмотрел в логах, прилетело обработанное исключение, все по плану. Хорошо.

**Comment by iprst** [comment]
Этот issue можно закрывать, насколько я понял?

**Comment by audetv** [comment]
да, для следующего этапа — переключение по условной фразе, если это будет необходимо, откроем другой.
