### ISSUE TITLE
Телеграм-канал https://t.me/svoddru

### ISSUE THREAD

**Issue by BlackPatrick** [terratensor/svodd#249]
У меня идея для развития телеграм-канал. Попробовать добавить в автоматическую трансляцию обсуждения имя автора на форуме ФКТ. В целом, при постоянном чтении уже есть понимание кто и кому отвечает, но наглядность бы не помешала. Чем на мой взгляд телеграм-канал лучше, чем чтение сообщений на форуме, так это автоматическое обновление ленты. Если читать только форум, то для просмотра новых сообщений надо все время обновлять страницу. Также на форуме браузер не запоминает где ты остановился при последнем подключении.

Есть ли техническая возможность добавить к трансляции автора сообщения?

**Comment by BlackPatrick** [comment]
Перенес вопрос в раздел про тг-бот

**Comment by audetv** [comment]
https://github.com/terratensor/tg-svodd-bot/issues/12#issue-1895875852
