### ISSUE TITLE
Разработать модуль, который бы обрезал ссылки на телегу в комментариях

### ISSUE THREAD

**Issue by audetv** [terratensor/svodd#255]
Есть такая идея к обсуждению. Предлагаю рассмотреть модуль для парсера сайта и телеграм канала, который бы обрезал ссылки на телегу, не затрагивая все остальные ссылки. То есть из ссылок вида 
```
https://t.me/aaaaabbbbb111111
```
Делал текст вида
```
t.me/aaaaabbbbb111111
```
Без создания прямой ссылки. Таким образом мусор не будет ретранслироваться в качестве прямых ссылок, что не позволит делать из ресурса ретрансляционную помойку.

_Originally posted by @iprst in https://github.com/terratensor/tg-svodd-bot/issues/15#issuecomment-1751701445_

**Comment by audetv** [comment]
Готово, обновлено, работает.

**Comment by BlackPatrick** [comment]
> Готово, обновлено, работает.

Обрезание ссылок перестало работать

**Comment by audetv** [comment]
Этот функционал работает только на сайте svodd.ru и в телеге svoddru.
Не работает и не работало на сайте ФКТ. Сайтом ФКТ мы не управляем, обсуждение на сайте ФКТ.
svodd — поиск и трансляция.

**Comment by BlackPatrick** [comment]
Я именно про работу в телеге svoddru.

**Comment by BlackPatrick** [comment]
> Этот функционал работает только на сайте svodd.ru и в телеге svoddru. Не работает и не работало на сайте ФКТ. Сайтом ФКТ мы не управляем, обсуждение на сайте ФКТ. svodd — поиск и трансляция.

Все. Я понял в чем дело. В приложении на мобильном эти обрезанные ссылки не работают, а если зайти через web-версию (что я и сделал, когда обнаружил), то там она не работает, и видимо и не должна работать

**Comment by audetv** [comment]
В телеге ссылка, которую обсуждали днем отображается, как и задумано:
<details><summary>Details</summary>
<p>

![2024-09-11_16-44-35](https://github.com/user-attachments/assets/0c741a57-8728-4697-982d-95bc069f3256)

</p>
</details> 

Ссылка не является активной гиперссылкой и по ней нельзя прейти по клику, но ее можно скопировать. Для этого в телеге перед ссылкой добавляется знак нижнего подчеркивания. Т.е. функционал с данного issue на данный момент работает как и задумано. Т.е. ссылки полностью не удалятся, они становятся не активными, и чтобы по ним перейти необходимо осуществить некоторые дополнительные осмысленные действия.

**Comment by BlackPatrick** [comment]
Выше уже ответил
