### ISSUE TITLE
Ссылка в тексте комментария #455033 ломает верстку

### ISSUE THREAD

**Issue by audetv** [terratensor/svodd#258]
[Комментарий 455033](https://svodd.ru/?search%5Bquery%5D=455033&search%5Bmatching%5D=&search%5Bmatching%5D=in&search%5Bdate%5D=&search%5Bdictionary%5D=0)
Множественные ссылки в перемешку со скобками и ссылкой на телегу и ютуб сломали верстку.
Парсер отработал нормально, в исходном тексте верстка валидная.
В телеграм боте парсер также отработал нормально, верстка валидная.
Проблема в функции TgLinkClipper, которая парсит ссылки на телегу и отображает в комментарии, надо переписать.
https://github.com/terratensor/svodd/blob/7ff3914bd9d4bfc39c11180b8e938ee9c0513690/app/src/helpers/TgLinkClipper.php#L9

**Comment by iprst** [comment]
Конструкцию `(t.me` нужно заменять на `_t.me`?

**Comment by audetv** [comment]
Я не хотел писать полноценный парсер, как в фкт-парсере и в телеграм боте, а отделаться регуляркой, 
скопировал, что попроще, работало, а как каша из ссылок не началась, сломалось)
Надо переписать, видимо подключу парсер, там функция почему то в тегах путается, открывающий / закрывающий при множественных совпадениях.

**Comment by audetv** [comment]
https://svodd.ru/?search%5Bquery%5D=455033&search%5Bmatching%5D=&search%5Bmatching%5D=in&search%5Bdate%5D=&search%5Bdictionary%5D=0
