### ISSUE TITLE
Проиндексировать комментарии под выпусками В-О

### ISSUE THREAD

**Issue by iprst** [terratensor/svodd#274]
Под выпусками передачи «Вопрос–Ответ» Валерия Викторовича публикуются комментарии, которые на текущий момент не учитываются в поиске и статистике. Предлагаю проиндексировать эти страницы, рассматривая каждую публикацию выпуска передачи как «вопрос» на сайте и поместить в общую систему. 

Адрес рубрики https://фкт-алтай.рф/qa/video/

**Comment by audetv** [comment]
Да, вариант хороший, я имею ввиду, что саму стенограмму считать вопросом и комментарии к ней, как комментарии.
Технически должно взлететь без особых «доработок напильником». Но пареср надо будет точно допилить, для обработки вопроса.
Стенограммы длинные… Но посмотрим. На сайте кремля длиннее.

**Comment by iprst** [comment]
Саму стенограмму можно не индексировать парсером для комментариев. Страница комментариев, насколько это понятно, свёрстана так же как под обычными вопросами. Но можно и проиндексировать, ведь они регулярно пополняются. 

Готовые (на тот момент) стенограммы В–О в разных форматах выкладывались ещё в прошлом году:
https://github.com/terratensor/transcript

**Comment by iprst** [comment]
Если индексировать стенограммы парсером, то в очень старых выпусках (примерно первые десять) вообще нет стенограммы, эти я делал вручную из транскрипции ютуба. Под некоторыми такими выпусками есть список заданных вопросов. Под другими вообще пустота. 

Но комментарии это отдельная тема, их, наверное, можно спарсить практически в стандартном режиме.

**Comment by audetv** [comment]
Реализован отдельный сервис, который индексирует выпуски В—О и комментарии.
https://github.com/terratensor/svodd-server
