### ISSUE TITLE
Специальный режим поиска по стенограммам В–О

### ISSUE THREAD

**Issue by iprst** [terratensor/svodd#291]
Планируется ли реализовать? Дабы клиент, желающий искать только в тексте стенограмм, мог выбрать соответствующую кнопку или пункт меню.

**Comment by iprst** [comment]
Думаю, нужно будет при открытии новой темы сделать анонс этого функционала. Возможно в отдельном посте-новости.

**Comment by audetv** [comment]
Да, хорошо, я планирую сегодня закончить. Уже сделал логику поиска, сейчас метки делаю цветные. К ночи закончу. И можно объявить, если что пойдет не по плану отпишусь.

**Comment by audetv** [comment]
Сделал обновление. Надо протестировать.
Замечания, предложения, и завтра буду исправлять если что.

**Comment by audetv** [comment]
Нашел баг. Надо исправить фильтр даты и маркера СВОДД, если выбираем и фильтр по дате и по маркеру СВОДД, то не работает фильтр по СВОДД, отображает все маркеры.

**Comment by iprst** [comment]
По багам пока ничего не попалось, но кажется нужно подумать над оформлением, сейчас слишком много контроллеров получается в одну кучу-малу. Предложения. 

- [ ] Уравнять расстояние между метками «`сводд` . `вопрос-ответ`» и «`вопрос-ответ` . . `комментарии`», сейчас слева разрыв в один пиксель, справа в два.
- [ ] Переместить метки из-под строки в заголовок страницы рядом с кнопкой `короткая ссылка`, при резиновой вёрстке три метки и кнопка склеиваются и переносятся вместе.
- [ ] Убрать дублирующие радиокнопки, оставить только метки.
- [ ] Переименовать сущности, сделав их более компактными: 
☉ Обычный поиск
☉ Точное соответствие
☉ Любое слово
☉ По номерам записей через запятую 
[✓] Концептуальный словарь

![image](https://github.com/user-attachments/assets/eac54a14-818f-4431-affd-2dea96857c4e)

**Comment by audetv** [comment]
Внес изменение, заодно переделал главное меню, добавил иконки как на feed.
Хлебные крошки со страницы поиска убрал совсем. Кажется их функционального смысла 0.
Заодно решена задача с отображением на мобильных, маркеры и кнопка будут на разных строках, и не будет хлебных крошек.

**Comment by iprst** [comment]
Отлично всё получается. Компактно. Поиск работает хорошо.

В некоторых сценариях режим поиска по номеру комментария не прямолинейный, например если номера из сводд, то при нажатом маркере «комментарии» ничего найдено не будет или наоборот. Если нажать «вопрос-ответ», то скорее всего вообще ни при каких цифрах ничего найдено не будет. В общем, тут видимо нужно подумать на более общем уровне, что это за функция.

**Comment by audetv** [comment]
Да, это правильное замечание. Я совсем об этом забыл, точнее выкинул из головы при реализации, чтобы не зациклиться)
Технически можно вытащить номера выпусков Вопрос ответ, они доступны на странице со списком выпусков в атрибуте  data-key
<details><summary>Details</summary>
<p>

![2024-07-20_14-33-24](https://github.com/user-attachments/assets/4da4b6d6-588f-4872-838b-1d4b8a1ff7aa)


</p>
</details> 

Я эти номера заметил позже, можно их добавить, но будет ли толк, потому как вряд ли кто-то из пользователей сможет эти номера читать, они спрятаны и недоступны. 

Таким образом да согласен надо подумать на более общем уровне, что это за функция.

**Comment by iprst** [comment]
> номера заметил позже, можно их добавить, но будет ли толк, потому как вряд ли кто-то из пользователей сможет эти номера читать, они спрятаны и недоступны

Сам функционал номеров редко, но используется — можно собрать «диалог по теме» из отобранных номерам комментариев. Я думаю это очень удачная функция для пока редкого сценария, когда будет больше пользователей это может стать более полезным на практике. По поводу маркеров, возможно при поиске по номерам нужно принудительно переключать маркеры в состояние «все»?

**Comment by audetv** [comment]
> По поводу маркеров, возможно при поиске по номерам нужно принудительно переключать маркеры в состояние «все»?

Да, вариант, сейчас сделаю и посмотрим, если что вернем обратно. Можно принудительно сбрасывать в состояние «все» и еще сделать метки disabled недоступными для нажатия. 
Можно было бы при нажатии на метку, сбрасывать поиск в режим 'Обычный поиск', но возможно тогда может быть непонятно с номером. т.е номер в строке указан и опять включены метки. А возможно, что это будет логично надо сделать и потыкать.

**Comment by audetv** [comment]
При реализации маркеров, ловил себя на мысли, ожидаю при нажатии на маркер появление результатов даже в том случае если не набран поисковый запрос. Но откидывал эту мысль. дабы не отвлекаться, но эта мысль меня продолжает преследовать. Реализовать технически это вообще не сложно, пару строк кода. но нужно ли.

Стоит ли включить такой режим фильтра, что при нажатии на метку при пустом поисковом запросе, поиск все равно бы выдавал результаты: весь список сущностей?

Кажется при таком сценарии немного ломается логика поиска и получается как будто бы пункт меню по которому доступны записи, типа как новости. Не понимаю, кажется что это может побудить пользователя поискать что то нужное ему в большом списке, т.е. включить произвольное внимание и вывести из автоматизма, или же я выдумываю и то ничего не дает. Не знаю. зачем я об этом думаю)

**Comment by iprst** [comment]
Такое ожидание было и у меня. Жмёшь маркер в пустом сайте, и получаешь: 
1. Всю соборную тему;
2. Все стенограммы В–О;
3. Все комментарии сайта. 

Насчёт психологии возможных реакций не берусь сказать, тут слишком сложная конструкция для оценки. Думаю какое-то побуждение может происходить, потому что «общая шевелёнка» обычно побуждает, но как будет на практике понятия не имею.

**Comment by iprst** [comment]
Пока тут добавлю наблюдение: картинки в стенограммах, попадающие на svodd.ru публикуются в режиме «как есть» или близко к тому, все картинки вразнобой, без выравнивания и отступов, совершенно разных размеров и так далее. Выглядит колхоз! 

[ПРИМЕР](https://svodd.ru/?sort=-datetime&search%5Bquery%5D=%D0%92%D0%B0%D0%BB%D0%B5%D1%80%D0%B8%D0%B9+%D0%92%D0%B8%D0%BA%D1%82%D0%BE%D1%80%D0%BE%D0%B2%D0%B8%D1%87%2C+%D0%BC%D1%8B+%D0%BA%D0%B0%D0%BA+%D0%B1%D1%8B+%D1%83%D0%B6%D0%B5+%D0%B2%D0%BE%D1%88%D0%BB%D0%B8+%D0%B2+%D0%BD%D0%B5%D0%BA%D0%B8%D0%B9+%D1%82%D0%B0%D0%BA%D0%BE%D0%B9+%D1%81%D0%B2%D0%BE%D0%B9+%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA+%D0%B2%D0%B5%D1%89%D0%B0%D0%BD%D0%B8%D1%8F&search%5Bmatching%5D=&search%5Bmatching%5D=match_phrase&search%5Bdate%5D=&search%5Bdictionary%5D=0&search%5Bbadge%5D=all)

**Comment by audetv** [comment]
Потому что их там не должно быть, этих картинок, это несанкционированное появление)
Айнис Казимирович Петкус: не входит в список ведущих и не сработал алгоритм деления на фрагменты-чанки, в таком случае если что-то пошло ни так, то текст В—О публикуется как есть, я так делал специально, но надо будет вырезать все картинки, для такого сценария. 

А как только добавим товарища Айнис Казимирович Петкус в список ведущих, весь колхоз пропадет. Хорошо получилось, нормальный опыт.

**Comment by iprst** [comment]
Айнис Казимирович Петкус прокрался и опубликовал изображения!

**Comment by audetv** [comment]
Исправлено.  А вот с картинками, которые попадают при таком сценарии надо будет разобраться, тему пока **не закрываем**.
И надо видимо какое-то автоматическое оповещение сделать, если подобный сценарий тс новым ведущим случился и надо обновить список. Подумаю.

**Comment by audetv** [comment]
Интересный-странный блок получился, сделал скриншот, чтобы разобраться, р=набрал в поиске, чтобы была ссылка…
Так это же случай с нашими лишними висящими пробелами.

<details><summary>Details</summary>
<p>

![2024-08-12_22-50-22](https://github.com/user-attachments/assets/7b8963cb-c82b-41f5-b201-f986188f9f2f)

</p>
</details> 

[Айнис Казимирович Петкус: Я утрирую, конечно, да.](https://svodd.ru/?sort=-datetime&search%5Bquery%5D=%D0%90%D0%B9%D0%BD%D0%B8%D1%81+%D0%9A%D0%B0%D0%B7%D0%B8%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B8%D1%87+%D0%9F%D0%B5%D1%82%D0%BA%D1%83%D1%81%3A+%D0%AF+%D1%83%D1%82%D1%80%D0%B8%D1%80%D1%83%D1%8E%2C+%D0%BA%D0%BE%D0%BD%D0%B5%D1%87%D0%BD%D0%BE%2C+%D0%B4%D0%B0.&search%5Bmatching%5D=&search%5Bmatching%5D=query_string&search%5Bdate%5D=&search%5Bdictionary%5D=0&search%5Bbadge%5D=aq)

**Comment by iprst** [comment]
> Так это же случай с нашими лишними висящими пробелами.

Так они, судя по всему, появились в ходе зачистки изображения с сайта stoletie

**Comment by audetv** [comment]
Да, в общем, нужна проверка на пустые чанки, посмотрю, это не критично, позже сделаю правку.
Да, про картинку я не подумал, но это логично. Спарсился блок, вырезалось запрещенное из него и остался пустой блок `''`, только с цитатой ведущего. И Валерий Викторович многозначительно …
