### ISSUE TITLE
Счётчик «пустых» вопросов на сайте

### ISSUE THREAD

**Issue by iprst** [terratensor/svodd#299]
Для отбора удобно представлять, какие пустые вопросы есть для открытия темы. Например, если бы вопросы без комментариев были отмечены флагом, и можно было бы отправить поисковый запрос только по ним, то на выходе был бы готовый к использованию набор вариантов для открытия новой темы. Сам счётчик полезен тем, что можно иметь общее представление о количестве таких пустых тем, но это скорее более-менее однократный интерес.

**Comment by audetv** [comment]
Ну, да понятно. Так то по всем вопросы уже известно, есть ли к ним комментарий или нет. Но это по вопросам в БД. Когда производится поиск, то ищется по другой бд manticore. В manticore нет этой информации, но в принципе, можно для каждого вопроса делать отдельный запрос в postgres перед выдачей в поиск, и проверять сколько у него комментариев и если 0, то как-нибудь отмечать его флагом. А вот как искать только по вопросам без комментариев пока не знаю. Надо подумать.
Вопросы с 0 комментариев начинаются с 493 страницы списка вопросов: https://svodd.ru/questions?sort=-comments_count&page=492
Но очевидно, что в таком режиме просмотра это не подходит для поиска вопроса для новой темы.

**Comment by iprst** [comment]
Сейчас тактики две — либо берётся текущая дата плюс пара недель, и ищется пустой вопрос в прошлом, начиная с самых старых; либо сначала представляется вектор развития событий и под него делается запрос на фкт, где уже выбираются вопросы, подходящие под критерии.

**Comment by audetv** [comment]
> Может быть просто выгрузить все вопросы с нулём?

Да, это можно сделать. Сделать свежий  дамп бд на текущий момент и по идее надо сделать sql запрос объединяющий 2 таблицы, одна со списком вопросов с текстом вопроса, а другая с номерами вопроса и количеством комментариев. И сохранить в csv. Попробую.

**Comment by iprst** [comment]
Это не суперсрочно. Удалось найти вопрос, отвечающий обеим тактикам буквально, так что пустые вопросы понадобятся не прямо сейчас.

**Comment by audetv** [comment]
Хорошо, сделаю ввгрузку позже. Может быть удастся придумать решение и без выгруки. Надо подумать, сходу вот прямо нет мыслей. Точнее, пока не сложилось в то, чтобы назвать мыслью , так обрывки, надо все обдумать спокойно в фоне.

**Comment by iprst** [comment]
Йес (с)

**Comment by audetv** [comment]
Добавлена сортировка в поиск.
Количество комментариев по возрастанию — https://svodd.ru/?sort=comments_count
Количество комментариев по убыванию — https://svodd.ru/?sort=-comments_count

**Comment by iprst** [comment]
Сейчас более четырёх тысяч пустых вопросов на сайте. Теперь их можно как просто пролистать с оценкой под выбор следующей темы, так и целенаправленно поискать среди них заданный вектор. Оба варианта работают, задача закрыта.

**Comment by iprst** [comment]
Счётчик пустых вопросов перестал работать: при выборе в поиске упорядочивания по количеству ответов, наверху списка с якобы пустыми вопросами в основном попадаются вопросы с комментариями в них. svodd.ru показывает 0 комментариев, а данные фкт отличаются, вопросы не пустые. 

Сейчас при открытии новой темы искал вручную по фкт подходящий пустой вопрос, наш счётчик не сработал.

**Comment by audetv** [comment]
Так, кажется понял, проверю гипотезу.
Сначала подумал, что сломал фильтр, когда  ранее осенью убирал возможность для незарегистрированных пользователей листать все 9000+ страниц в поиске, чтобы боты сильно наглели. Но это не оно.
Похоже сбой из-за  восстановления базы, осеннее падение и перезагрузки сервера в итоге привели к тому, что поломалась база postgres, я восстанавливал полностью данные из бэкапа. Надо будет посмотреть, вспомнить, изучить заново, как это работает, возможно надо счетчик статистики запустить. Поправлю.

**Comment by audetv** [comment]
Исправил, сейчас работает. Конечно теперь ни скоро пригодится, но как есть. Действительно, надо было запустить команду обновления статистики комментариев для всей базы. 
Все вопросы, в которых были новые комментарии (новые вопросы и соборная тема), обновляли статистку с каждым комментарием, а остальные вопросы записаны с нулями. Поле для хранения количества комментариев в индексе мантикоры я добавлял позднее.
И не добавил выполнение команды установки количества комментариев в вопросе при создании нового поискового индекса, торопился и сценарий не частый. @todo Надо добавить!, Сейчас получается, что если обнулил поисковый индекс и собираешь его заново, то данные о количестве комментариев в вопросе не приходят в индекс, записывается 0, поэтому  после индексации надо отдельно запустить команду `php yii index/update-statistic` для обновления статистики всех вопросов и комментариев.

**Comment by iprst** [comment]
Почему не скоро, можно через две недели открыть новую тему
