### ISSUE TITLE
Невозможно зайти на сайт. Chrome / Android

### ISSUE THREAD

**Issue by iprst** [terratensor/svodd#328]
Версии андроида 5, 6 и 7 перестали позволять зайти на сайт через chrome. При этом сначала отваливались более новые версии системы, а потом перестали работать и старые. 

> Подключение не защищено
>
>Злоумышленники могут пытаться похитить ваши данные с сайта svodd.ru (например, пароли, сообщения или номера банковских карт). [Подробнее…](chrome-error://chromewebdata/#)
NET::ERR_CERT_AUTHORITY_INVALID
>
>Чтобы браузер Chrome стал максимально безопасным, [включите режим "Улучшенная защита"](chrome-error://chromewebdata/#).
>
>На сайте svodd.ru для защиты ваших данных обычно используется шифрование. Однако учетные данные, которые мы получили от сайта svodd.ru сейчас, отличаются от тех, которые он отправляет обычно. Вероятно, вредоносный сайт пытается выдать себя за svodd.ru или страница подключения к сети Wi-Fi прервала соединение. Ваша информация по-прежнему в безопасности, так как Chrome разорвал соединение до того, как произошел обмен данными.
>
>Веб-сайт svodd.ru использует механизм HSTS. Открыть сайт в настоящее время нельзя. Сбой мог быть вызван сетевой ошибкой или действиями злоумышленников. Скорее всего, сайт заработает через некоторое время.

Ранее сайт работал на всех устройствах и всех версиях хрома, со всеми вариантами настроек безопасности. Пару-тройку дней назад перестали работать более свежие системы, а сейчас не работают и старые.

UPD: mozilla firefox открывает сайт без предупреждений и ошибок.
Установка сертификата Минцифры не меняет положения дел.

**Comment by iprst** [comment]
До 21 числа я только со смартфона вследствие форс-мажора. Где-то буду медленнее.

**Comment by audetv** [comment]
Возможно, что такое поведение может быть связно с тем, что с 15.08 на 16.08 мне пришлось прописать новый ns server'а и делегировать домен по новым правилам селктел. Делегирование произошло Обновлено: 16.08.24, 07:04:28. После этого в течение 3 суток могут наблюдаться проблемы, с доступом в различных точках, у разных провайдеров, пока новые данные распространятся по всем база интернета. Но это не точно. Я пока не могу найти иной причины, которая могла бы быть следствием изменений сделанных мной, зависящей от меня. 

Предлагаю так, если ситуация не измениться к понедельнику, то к вечеру, я попробую перевыпустить сертификаты Let's Encrypt tls, возможно сделаю это раньше надо посмотреть как, сейчас выпуск производиться автоматически, так настроена система, один раз в три месяца. Технически сертифкаты не привязаны к ns серверам только к имени домена, но возможно, при смене DNS, вызвало такое поведение. Подумаю, что может быть ещё, но пока это единственное, что похоже на причину. Да, старые андроиды, но сертификаты Let's Encrypt, это их родные эльфиские сертификаты. 

И ещё с 19 на 20 ночью, другой провайдер, тот где расположена инфраструктура , проводит смену своего движка. Я делал в дискуссиях сообщение. Обещают, что все будет ок, но бэкапы буду делать завтра. Так что если вдруг в понедельник сайт упадет, то это что-то пошло ни так у провайдера. В таком случае есть большая вероятность, что я только к вечеру смогу восстановить работоспособность сайта. Если пойдет по сценарию, что у провайдер будет сбой обязательно напишу в гите.

**Comment by iprst** [comment]
Обновление может и связано, однако основная причина в другом, поскольку проявилась раньше, как минимум 13 августа.

**Comment by iprst** [comment]
Спешки нет, отслеживать тему можно в телеграме. Но работает неправильно и кажется это гугл компостирует мозги, например в мобильном фаерфоксе сайт открывается нормально.

**Comment by audetv** [comment]
Запустил старый телефон с андроидом 4.2. пишет, что у этого сата проблема сертификатом безопасности. Нажимаю посмотреть сертификат, пишет получен из ненадежных источников… R10 Let`s Encrypt. Но сайт можно посмотреть, нажимаю, все равно перейти и сайт работает. Правда т.к. это bootsrap 5 flex, то css не работает как надо, сайт выглядит, как без стилей.  Думаю вряд ли связно с обновлением ns, я запустил со своей wifi сети и получил ошибку сертификата, браузер встроенный AgentMozilla/5.0. У старых браузеров я несколько раз точно сталкивался с проблемой сертификатами, я но как то не заострял на этом внимание, не разбирался, просто считал, что самой собой на старом браузере может быть ошибка. Почитаю, по возможности.

>  Но работает неправильно

А что значит работает не правильно, выдает ошибку типа:  у этого сата проблема сертификатом безопасности. Или еще что то? Типа стили не грузятся.

<details><summary>Details</summary>
<p>

![photo_2024-08-17_22-18-18](https://github.com/user-attachments/assets/2cbcb4ff-0fe5-45f4-bbc1-9588342abff9)


</p>
</details>

**Comment by audetv** [comment]
Почитал немного, возможно поможет установка особого корневого сертификата. 
Поиск в яндексе с первых строк ведет на страницы, где написано, что LetsEncrypt сертификаты не работают на старых андроидах, например по запросу: [android 4.2 сертификаты lets encrypt](https://ya.ru/search/?text=android+4.2+%D1%81%D0%B5%D1%80%D1%82%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D1%8B+lets+encrypt&lr=2)

У Let's Encrypt существует проблема с устройствами до  7.1.1. На сайтах svodd сертификат Let's Encrypt, потому что бесплатно, срок на 3 месяца и настроен автоматический перевыпуск.
Возможно поможет установка специально корневого сертификата

https://letsencrypt.org/2020/12/21/extending-android-compatibility.html

https://server-support.co/apple/software/how-to-make-older-android-devices-work-with-letsencrypt-root-certificate/

**Comment by iprst** [comment]
Работает неправильно = выдаёт ошибку как в заглавном сообщении.

**Comment by audetv** [comment]
Я по второй ссылке ссылке https://server-support.co/apple/software/how-to-make-older-android-devices-work-with-letsencrypt-root-certificate/
Скачал сертификат по ссылке на той странице: https://letsencrypt.org/certs/isrgrootx1.der
Я его переименовал в `isrgroot1.cer` но возможно это не надо делать, разрешил устанавливать приложения из других источников, установил сертификат пользователя Безопасность (Надежные сертифкатs, Установка с SD карты) На разных версиях андроида наименования пунктов меню могут различаться. И после этого сайты имеют замочек в строке браузера и предупреждение больше не появляется, но стили в браузере не отображаются, на системе 2014 года

**Comment by audetv** [comment]
Посмотрел, по тем данным, что отображаются в телефоне при просмотре сертификата, нашел его, данные визуально совпадают: https://crt.sh/?id=9314791
Там же на этой странице можно сертификат скачать Download Certificate: [PEM](https://crt.sh/?d=9314791)
Установил на телефон, работает. Полагаю файл в последнем сообщении, более надежный.

**Comment by iprst** [comment]
Да, тоже установил по второй ссылке сертификат и также сначала переименовал расширение файла (оригинал поставить нельзя), хром перестал ругаться и сайт открывается.

**Comment by iprst** [comment]
### Рабочие решения

1. Не требует переименования файла:
> на этой странице можно сертификат скачать Download Certificate: [PEM](https://crt.sh/?d=9314791)

2. Требует переименования файла:
> сертификат по ссылке на той странице https://letsencrypt.org/certs/isrgrootx1.der
> Я его переименовал в `isrgroot1.cer`

Скачанный файл сертификата установить средствами ОС смартфона.  Для этого в настройках поискать «сертификат» и выбрать подходящий пункт меню типа «установка сертификата». Результат одинаковый, сайт работает. Другие сайты с подобной проблемой также излечиваются.
