### ISSUE TITLE
Телеграм не обновляет комментарии

### ISSUE THREAD

**Issue by iprst** [terratensor/svodd#360]
Последний опубликованный в телеге от 0:08 15.12.2024 (про два танкера). 
В приложении и в браузере картина одна и та же.

**Comment by iprst** [comment]
Сайт также не обновляет комментарии. Последний комментарий темы тот же, что в телеграме. 
https://github.com/terratensor/fct-parser/issues/24

**Comment by audetv** [comment]
Спасибо. Восстановлено.

**Comment by iprst** [comment]
Да, работает и сайт и тележка.
